language: go
go:
- 1.9.2
env:
  - NODE_VERSION="6.10.0"
before_install:
  - nvm install $NODE_VERSION
install: true
notifications:
  email: false
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get github.com/golang/lint/golint
- go get github.com/apprentice3d/forge-api-go-client
script:
- go test -v -race ./...
- go vet ./...
- golint -set_exit_status $(go list ./...)
- cd ./frontend_src
- npm install
- npm run build
- cd ..
- env GOOS=linux GOARCH=amd64 go build -v -o ./bin/linux/forge-photo23d
- env GOOS=windows GOARCH=amd64 go build -v -o ./bin/windows/forge-photo23d.exe
- env GOOS=darwin GOARCH=amd64 go build -v -o ./bin/osx/forge-photo23d
- cp -R ./client/ ./bin/linux/client
- cp -R ./client/ ./bin/windows/client
- cp -R ./client/ ./bin/osx/client
- cd ./bin/linux && zip -r linux.zip .
- cd ../../bin/windows && zip -r windows.zip .
- cd ../../bin/osx && zip -r osx.zip .
- cd ../..
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hSzMw4JxZ1YdU4efo87JEBRYI2nipgrGrgCDdksm40/UI2iMgWa39jYPJXJ505SKkeG58MxxQkC3MPE9bOheWdbzQ5YL04kJfZ8ngmlq2IGkZtTz36H7oGR3PYWTno0AvaqzLSjKbmOaBbo1xGHqEXoV5TAwNFsIdjvCMa/R8DCblQFQDa2TM36+8ckyEYNSi+WfP0zQh9GOguM2uLhErI+XSlPGaGqejPvvmVNCbIYlWOJ9RWfNAsjUm9pDCcXrb3bE4uT38RV/Nmbp06bLVlRjAyjFQGKUJz4pGNYFJSUHqgGyQz7ITgZwHdpQNqst+S/qljGs0NQnv3+OxYZyuAVvU/DeHYTl4HTNMoE/d38WrQEqd/Gre6HUJRmvrpuVRPz2EWhkosl4hKKcm44yU6BS9jSpg0LSwd4KgHQMH9MNJmoJ0PxnDg3bT+qSPigvEyZYARJr9JuMBBBWRYseRvhKPYZUE13X/OwUyZQXXwS/q6HSV0PR0DZaUaZJIfLfHtQK0rjch8G5PNjzU68U3q3oog4kbY5caXggAfyQraqLnV9rqmbIINLWfkqc6uUbvwoKLCTtBIwTe1pWmCAdfqhJSu1NDb6aRTS2KymZjo3s7Wt8CwB37c72Ci08WuX6xEMZMFt43etyMCV5S0fVCeRyYyV/QlxAfJ3VjpwNgJ0=
  file:
  - ./bin/linux/linux.zip
  - ./bin/windows/windows.zip
  - ./bin/osx/osx.zip
  on:
    tags: true
    repo: apprentice3d/forge-photoII3D
